version: '3.8'

services:
  transfer_calculator:
    build:
      context: .
      dockerfile: Dockerfile
    
    container_name: transfer_calculator
    
    ports:
      - "3000:3000"
    
    environment:
      - NODE_ENV=production
      - PORT=3000
    
    restart: unless-stopped
    
    # Limites de recursos
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    
    # Volumes (opcional, para persistência de logs)
    volumes:
      - ./logs:/app/logs
    
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Healthcheck
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Volumes nomeados (opcional)
volumes:
  logs:
    driver: local

